# Generated by Django 4.1.1 on 2022-10-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('shipment_status_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipment_status',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('shipment_code', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('shipment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipmentstatus')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
    ]
