# Generated by Django 4.1.1 on 2022-10-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePositionStatus',
            fields=[
                ('warehouse_position_status_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouse_position_status',
            },
        ),
        migrations.CreateModel(
            name='WarehousePosition',
            fields=[
                ('warehouse_position_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_position_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousepositionstatus')),
            ],
            options={
                'db_table': 'warehouse_position',
            },
        ),
    ]
